# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datet',
            old_name='datetime',
            new_name='datet',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='datetime',
            new_name='datet',
        ),
    ]
