# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170324_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 12, 48, 31, 157989)),
        ),
    ]
