# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170324_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 14, 33, 38, 591599)),
        ),
    ]
