# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170327_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 14, 41, 1, 266449)),
        ),
    ]
