# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170327_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 10, 21, 30, 144219)),
        ),
    ]
