# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170405_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 18, 58, 900651)),
        ),
    ]
