# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20170405_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 28, 53, 999957)),
        ),
    ]
