# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20170405_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 19, 15, 33, 20, 42397)),
        ),
    ]
