# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20170421_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 25, 8, 54, 4, 519108)),
        ),
    ]
