# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20170425_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 25, 9, 34, 0, 89364)),
        ),
    ]
